version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: ./mvnw verify -Djpt.btf.provision=true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: ./target/jpt-workspace
      - store_test_results:
          path: ./target/failsafe-reports
